### ISSUE TITLE
Could not fit a model

### ISSUE THREAD

**Issue by Lxb-qqyb** [maxibor/pydamage#7]
I used pydamage to analysis WES bam files,but program shows “Could not fit a model for 7 because of too few reads aligned (4539592)”,same with the other chromosomes.What can we do about it?Is it not suitable for WES? And can give me a description of the result. Thanks.

**Comment by maxibor** [comment]
Hi @Lxb-qqyb ,
The model is not fitting because the minimum threshold for coverage is not met.
You can decrease it with `-c` to something lower than 8 (depending on the coverage you have for each chromosome).
Pydamage is not yet published, and I'm on vacation right now, but I will give an update when I'm back 😃

**Comment by maxibor** [comment]
Checking back on you @Lxb-qqyb : did you manage to make it run with the above suggestions ?

Also, the documenation has been updated to describe the output: https://pydamage.readthedocs.io/en/latest/output.html
